# Get all persons.

GET http://localhost:9080/JEE-App/api/persons

###

# Create a new person

PUT http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951
Content-Type: application/json

{
  "firstName": "Jacob",
  "moneyInBankAcc": 1000.24,
  "lastName": "Markale",
  "dateOfBirth": "812981280000"
}

###

# Get a single person.

GET http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951

###

# Get a person photo

GET http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951/photo

###


# Create a person photo

PUT http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951/photo
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="WW.png'

< JEE-App/src/main/resources/WW.png
--boundary--

###

# Update a person photo

PATCH http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951/photo
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="JP.png'

< JEE-App/src/main/resources/JP.png
--boundary--

###

# Update a person

PATCH http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951
Content-Type: application/json

{
  "moneyInBankAcc": 12.73,
  "lastName": "Broke"
}

###

# Delete a person

DELETE http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951

###

# Get all categories

GET http://localhost:9080/JEE-App/api/categories

###

# Create a new category

PUT http://localhost:9080/JEE-App/api/categories/a786fdf4-e0b6-4360-98cb-dab711d57953
Content-Type: application/json

{
  "whereWearClothing": "HEAD",
  "name": "Beret",
  "isTrendy": true
}

###

# Get a single category

GET http://localhost:9080/JEE-App/api/categories/a786fdf4-e0b6-4360-98cb-dab711d57953

###

# Update a category

PATCH http://localhost:9080/JEE-App/api/categories/a786fdf4-e0b6-4360-98cb-dab711d57953
Content-Type: application/json

{
  "isTrendy": false
}

###

# Delete a category

DELETE http://localhost:9080/JEE-App/api/categories/a786fdf4-e0b6-4360-98cb-dab711d57953


###

# Get all pieces

GET http://localhost:9080/JEE-App/api/pieces

###

# Create a new piece

PUT http://localhost:9080/JEE-App/api/pieces/a786fdf4-e0b6-4360-98cb-dab711d57952
Content-Type: application/json

{
  "resellPrice": 43.21,
  "name": "Super fajny t-shirt 3000",
  "size": "XL"
}

###

# Get a single piece

GET http://localhost:9080/JEE-App/api/pieces/a786fdf4-e0b6-4360-98cb-dab711d57952

###

# Update a piece

PATCH http://localhost:9080/JEE-App/api/pieces/a786fdf4-e0b6-4360-98cb-dab711d57952
Content-Type: application/json

{
  "resellPrice": 12.73
}

###

# Assign a person to a piece
POST http://localhost:9080/JEE-App/api/pieces/a786fdf4-e0b6-4360-98cb-dab711d57952/persons/a786fdf4-e0b6-4360-98cb-dab711d57951

###

# Assign a category to a piece

POST http://localhost:9080/JEE-App/api/pieces/a786fdf4-e0b6-4360-98cb-dab711d57952/categories/a786fdf4-e0b6-4360-98cb-dab711d57953


###

# Delete a piece

DELETE http://localhost:9080/JEE-App/api/pieces/a786fdf4-e0b6-4360-98cb-dab711d57952