# Get all persons.

GET http://localhost:9080/JEE-App/api/persons

###

# Create a new person

PUT http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951
Content-Type: application/json

{
  "firstName": "Jacob",
  "moneyInBankAcc": 1000.24,
  "lastName": "Markale",
  "dateOfBirth": "812981280000"
}

###

# Get a single person.

GET http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951

###

# Get a person photo

GET http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951/photo

###


# Create a person photo

PUT http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951/photo
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="WW.png'

< JEE-App/src/main/resources/WW.png
--boundary--

###

# Update a person photo

PATCH http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951/photo
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="JP.png'

< JEE-App/src/main/resources/JP.png
--boundary--

###

# Update a person

PATCH http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951
Content-Type: application/json

{
  "moneyInBankAcc": 12.73,
  "lastName": "Broke"
}

###

# Delete a person

DELETE http://localhost:9080/JEE-App/api/persons/a786fdf4-e0b6-4360-98cb-dab711d57951

###

