# Get all persons.

GET http://localhost:9080/JEE-App/api/persons

###

# Get single person.

GET http://localhost:9080/JEE-App/api/persons/9e0f75ec-479e-40f8-b6db-d5a25fcdaa0e

###

# Get single character portrait.

GET http://localhost:9080/JEE-App/api/persons/9e0f75ec-479e-40f8-b6db-d5a25fcdaa0e/photo

###

# Create new character.

PUT http://localhost:9080/JEE-App/api/persons/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json

{
  "firstName": "Mark",
  "moneyInBankAcc": 1000.24,
  "lastName": "Jacobale",
  "dateOfBirth": "812981280000"
}

###

# Create character portrait.

PUT http://localhost:9080/JEE-App/api/persons/9e0f75ec-479e-40f8-b6db-d5a25fcdaa0e/photo
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="sigrid.png'

< JEE-App/src/main/resources/WW.png
--boundary--

###

# Update character.

PATCH http://localhost:9080/JEE-App/api/persons/0804a232-6910-4c89-8561-864ea7f22a36
Content-Type: application/json

{
  "moneyInBankAcc": 12.73,
  "lastName": "Broke"
}

###

# Delete character.

DELETE http://localhost:9080/JEE-App/api/persons/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

###

